name: caching-ci-demo

on:
  push:
     branches: [main]

jobs:
    test-cache:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Python/Setup python
              uses: actions/setup-python@v4
              with:
                python-version: 3.12

            - name: Cache pip dependencies
              uses: actions/cache@v3
              with:
                path: ~/.cache/pip
                key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Run code
              run: python test.py